version: "3"
services:
  web:
    image: sumeetsp07/sassbankserver:v2
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    depends_on:
      - mysqlhost
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  mysqlhost:
    image: sumeetsp07/sassbankmysql:v1
    volumes:
      - "/opt/sass/sassbank_mysqldata:/var/lib/mysql"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:


